[workspace]
resolver = "3"
members = [
    "velox-core",
    "velox-sfc",
    "velox-dom",
    "velox-renderer",
    "velox-style",
    "velox-cli",
    "examples/todo",
    "examples/gallery",

    "examples/demoapp2",

    "examples/demoapp3",

    "examples/myapp",

    "examples/demoapp4",
]
