// @generated by velox-sfc (stub)
#![allow(clippy::vec_init_then_push, clippy::arc_with_non_send_sync, clippy::blocks_in_conditions, clippy::duplicate_mod, clippy::match_single_binding, clippy::needless_borrows_for_generic_args, clippy::useless_format, unused_variables)]
use std::cell::RefCell;
use std::collections::HashMap;

/// Type alias for callback maps passed to child components.
pub type Callbacks = std::collections::HashMap<&'static str, &'static str>;

/// One handler a parent hands a child, as something the child can call.
///
/// `Rc<RefCell<dyn FnMut(&str)>>`, and the shape is not decoration — both
/// halves of it are load-bearing:
///
/// - The `Rc` is what makes a re-entrant call possible. A `Box<dyn FnMut>`
///   is owned by the registry cell, so calling it means calling it while
///   that cell is still borrowed, and a handler that emitted in turn would
///   panic on the second borrow. Cloning the handle out first leaves the
///   registry unborrowed for the whole call. The registry is thread-local,
///   so the handle never has to be `Send`.
/// - The inner `RefCell` is what makes the handle callable at all. `Fn`/`FnMut`
///   are implemented for `Box<F>` and for `&F`, but NOT for `Rc<F>`, so
///   `Rc<dyn FnMut(..)>` cannot be called without a `DerefMut` that `Rc` does
///   not implement. The inner cell is where the `&mut` comes from; the
///   registration itself is never removed, so a handler that panics does not
///   take its own binding down with it.
pub type EventHandler = std::rc::Rc<std::cell::RefCell<dyn FnMut(&str)>>;

// Thread-local callback registry for emit system.
// Stores event name -> handler function name mappings.
thread_local! {
    static EMIT_CALLBACKS: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
    // Handler name -> the call that runs it. Written by the parent that
    // rendered this component, read by `emit` and `dispatch_emit`.
    static EMIT_DISPATCH: RefCell<HashMap<String, EventHandler>> = RefCell::new(HashMap::new());
    static SLOTS: RefCell<HashMap<String, velox_dom::VNode>> = RefCell::new(HashMap::new());
}

/// Register callbacks for the current render scope.
/// Called by `render_with_callbacks` before rendering a child component.
pub fn set_emit_callbacks(callbacks: &Callbacks) {
    EMIT_CALLBACKS.with(|cell| {
        let mut map = cell.borrow_mut();
        map.clear();
        for (k, v) in callbacks {
            map.insert(k.to_string(), v.to_string());
        }
    });
}

/// Store slots for the current render scope so `<slot>` elements can find them.
pub fn set_slots(slots: &std::collections::HashMap<&str, velox_dom::VNode>) {
    SLOTS.with(|cell| {
        let mut map = cell.borrow_mut();
        map.clear();
        for (k, v) in slots {
            map.insert(k.to_string(), v.clone());
        }
    });
}

/// Register the call that runs one handler, keyed by the handler NAME the
/// parent wrote on the tag (`@confirm="on_confirm"` registers `on_confirm`).
///
/// A parent calls this for every handler it binds, immediately before it
/// calls `render_with_callbacks` / `render_with_slots`, and the call it
/// passes is its own event dispatcher: so the payload a child emits lands on
/// the parent's `State` method, with the arity the method declared already
/// decided by the dispatcher.
///
/// Registering a name twice replaces the call, so one component rendered
/// twice in a pass under different handlers is last-wins rather than both.
pub fn set_emit_dispatch(handler: &str, call: EventHandler) {
    EMIT_DISPATCH.with(|cell| {
        cell.borrow_mut().insert(handler.to_string(), call);
    });
}

/// Run the handler registered under `handler` with `payload`.
///
/// This is the entry point a FUNCTION-TYPED prop goes through: a parent
/// binding `:on_confirm="on_confirm"` hands the child a closure that calls
/// this with the name it read off the binding, so a child that prefers a
/// callable prop over `emit("..")` reaches exactly the same handler.
///
/// Returns whether a handler was registered, so a caller can tell a handler
/// that ran and decided to do nothing from one that was never bound.
pub fn dispatch_emit(handler: &str, payload: &str) -> bool {
    // Clone the handle out so the call happens with the registry cell
    // unborrowed — a handler that emits in turn reaches this function again
    // while its own call is still on the stack.
    let call = EMIT_DISPATCH.with(|cell| cell.borrow().get(handler).cloned());
    let Some(call) = call else { return false };
    (call.borrow_mut())(payload);
    true
}

/// Emit an event from a child component to its parent.
///
/// Resolves the handler the parent bound for `event` and RUNS it: the
/// dispatcher the parent registered is invoked with `payload`, which is what
/// reaches the parent's `State` method. Returns the handler name it
/// resolved, or `None` when the parent bound no handler for this event —
/// the one case where an emit has nowhere to go.
pub fn emit(event: &str, payload: &str) -> Option<String> {
    let handler = EMIT_CALLBACKS.with(|cell| cell.borrow().get(event).cloned())?;
    dispatch_emit(&handler, payload);
    Some(handler)
}

/// Look up slot content by name. Returns the slot VNode if found,
/// otherwise calls the fallback closure.
pub fn render_slot(
    name: &str,
    fallback: impl FnOnce() -> velox_dom::VNode,
) -> velox_dom::VNode {
    SLOTS.with(|cell| {
        let map = cell.borrow();
        if let Some(v) = map.get(name) {
            return v.clone();
        }
        drop(map);
        fallback()
    })
}

pub const TEMPLATE: &str = r#"
<div class="parent">
  <PropsChild :greeting="who" :count="how_many" />
</div>
"#;
pub const SCRIPT_SETUP: &str = r#"
import PropsChild from './props_child.vx'

pub struct State {
    pub who_value: String,
    pub count_value: String,
}

impl State {
    pub fn new() -> Self {
        State { who_value: String::new(), count_value: String::new() }
    }

    pub fn who(&self) -> String {
        self.who_value.clone()
    }

    pub fn how_many(&self) -> String {
        self.count_value.clone()
    }
}
"#;
pub const SCRIPT: &str = r#""#;
pub const STYLE: &str = r#""#;
pub const SCOPE_ID: &str = "";
pub mod script_rs {
    #![allow(unused_variables, unused_imports, unused_mut, unused_assignments, clippy::new_without_default)]
    use super::*;
    
    
    pub struct State {
        pub who_value: String,
        pub count_value: String,
    }
    
    impl State {
        pub fn new() -> Self {
            State { who_value: String::new(), count_value: String::new() }
        }
    
        pub fn who(&self) -> String {
            self.who_value.clone()
        }
    
        pub fn how_many(&self) -> String {
            self.count_value.clone()
        }
    }
}
/// This component declares no `Props` struct, so a parent binds nothing to it.
pub struct PropsArg {
    pub values: std::collections::HashMap<String, String>,
}

/// Render this component with callbacks from a parent component.
/// The callbacks map event names to parent handler method names.
pub fn render_with_callbacks(
    props: PropsArg,
    callbacks: &std::collections::HashMap<&'static str, &'static str>,
    _handler_names: &[&'static str],
) -> velox_dom::VNode {
    // Register callbacks in thread-local storage so emit() can find them.
    // set_emit_callbacks lives at the same level as this function (both inside
    // the component module), so no path qualifier is needed.
    set_emit_callbacks(callbacks);
    // Render using the standard props path
    render_with_props(props)
}

/// Render this component with callbacks and slots from a parent component.
/// The callbacks map event names to parent handler method names.
/// The slots map slot names to pre-rendered VNode trees.
pub fn render_with_slots(
    props: PropsArg,
    callbacks: &std::collections::HashMap<&'static str, &'static str>,
    _handler_names: &[&'static str],
    slots: &std::collections::HashMap<&str, velox_dom::VNode>,
) -> velox_dom::VNode {
    set_emit_callbacks(callbacks);
    set_slots(slots);
    render_with_props(props)
}

/// Render this component with slot content from a parent component.
/// The slots map maps slot names to pre-rendered VNode trees.
///
/// Distinct from `render_with_slots` above rather than another arity of it:
/// Rust resolves calls by name, so two functions with one name is a
/// duplicate definition however many arguments each takes.
pub fn render_with_slots_only(
    props: PropsArg,
    slots: &std::collections::HashMap<&str, velox_dom::VNode>,
) -> velox_dom::VNode {
    set_slots(slots);
    render_with_props(props)
}

use super::props_child as PropsChild;


pub fn render() -> velox_dom::VNode {
    render_with(|_| String::new())
}

pub fn render_with<F>(mut resolve: F) -> velox_dom::VNode where F: FnMut(&str) -> String {
    use velox_dom::*;
    h("div", Props::new().set("class", "parent"), { let mut __children: Vec<velox_dom::VNode> = Vec::new();
__children.push(text(" "));
__children.push({ let __props = PropsChild::PropsArg { greeting: resolve("who").clone(), count: (resolve("how_many").clone()).parse().unwrap_or_default() }; PropsChild::render_with_props(__props) });
__children.push(text(" "));
__children
})
}

#[allow(clippy::arc_with_non_send_sync)]
#[allow(unused_variables)]
pub fn render_with_state<F>(state: std::sync::Arc<script_rs::State>, mut resolve: F) -> velox_dom::VNode where F: FnMut(&str) -> String {
    use velox_dom::*;
    h("div", Props::new().set("class", "parent"), { let mut __children: Vec<velox_dom::VNode> = Vec::new();
__children.push(text(" "));
__children.push({ let __props = PropsChild::PropsArg { greeting: resolve("who").clone(), count: (resolve("how_many").clone()).parse().unwrap_or_default() }; PropsChild::render_with_props(__props) });
__children.push(text(" "));
__children
})
}

#[allow(clippy::arc_with_non_send_sync)]
pub fn make_resolve(state: std::sync::Arc<script_rs::State>) -> impl FnMut(&str) -> String {
    move |name: &str| match name {
        "who" => state.who().to_string(),
        "how_many" => state.how_many().to_string(),
        _ => String::new(),
    }
}

#[allow(clippy::arc_with_non_send_sync, clippy::single_match)]
pub fn make_on_event(state: std::sync::Arc<script_rs::State>) -> impl FnMut(&str, Option<&str>) + 'static {
    move |name: &str, payload: Option<&str>| {
        match name {
            _ => {}
        }
    }
}

pub fn render_with_props(props: PropsArg) -> velox_dom::VNode {
    let resolve_props = |key: &str| -> String {
        props.values.get(key).cloned().unwrap_or_default()
    };
    render_with(resolve_props)
}