// @generated by velox-sfc (stub)
#![allow(clippy::vec_init_then_push, clippy::arc_with_non_send_sync, clippy::blocks_in_conditions, clippy::duplicate_mod, clippy::match_single_binding, clippy::needless_borrows_for_generic_args, clippy::useless_format, unused_variables)]
use std::cell::RefCell;
use std::collections::HashMap;

/// Type alias for callback maps passed to child components.
pub type Callbacks = std::collections::HashMap<&'static str, &'static str>;

// Thread-local callback registry for emit system.
// Stores event name -> handler function name mappings.
thread_local! {
    static EMIT_CALLBACKS: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
    static SLOTS: RefCell<HashMap<String, velox_dom::VNode>> = RefCell::new(HashMap::new());
}

/// Register callbacks for the current render scope.
/// Called by `render_with_callbacks` before rendering a child component.
pub fn set_emit_callbacks(callbacks: &Callbacks) {
    EMIT_CALLBACKS.with(|cell| {
        let mut map = cell.borrow_mut();
        map.clear();
        for (k, v) in callbacks {
            map.insert(k.to_string(), v.to_string());
        }
    });
}

/// Store slots for the current render scope so `<slot>` elements can find them.
pub fn set_slots(slots: &std::collections::HashMap<&str, velox_dom::VNode>) {
    SLOTS.with(|cell| {
        let mut map = cell.borrow_mut();
        map.clear();
        for (k, v) in slots {
            map.insert(k.to_string(), v.clone());
        }
    });
}

/// Emit an event from a child component to its parent.
/// Looks up the registered callback and returns the handler name.
/// The caller is responsible for invoking the handler on their State.
pub fn emit(event: &str, _payload: &str) -> Option<String> {
    EMIT_CALLBACKS.with(|cell| {
        let map = cell.borrow();
        map.get(event).cloned()
    })
}

/// Look up slot content by name. Returns the slot VNode if found,
/// otherwise calls the fallback closure.
pub fn render_slot(
    name: &str,
    fallback: impl FnOnce() -> velox_dom::VNode,
) -> velox_dom::VNode {
    SLOTS.with(|cell| {
        let map = cell.borrow();
        if let Some(v) = map.get(name) {
            return v.clone();
        }
        drop(map);
        fallback()
    })
}

pub const TEMPLATE: &str = r#"
<div class="parent">
  <PropsChild :greeting="who" :count="how_many" />
</div>
"#;
pub const SCRIPT_SETUP: &str = r#"
import PropsChild from './props_child.vx'

pub struct State {
    pub who_value: String,
    pub count_value: String,
}

impl State {
    pub fn new() -> Self {
        State { who_value: String::new(), count_value: String::new() }
    }

    pub fn who(&self) -> String {
        self.who_value.clone()
    }

    pub fn how_many(&self) -> String {
        self.count_value.clone()
    }
}
"#;
pub const SCRIPT: &str = r#""#;
pub const STYLE: &str = r#""#;
pub const SCOPE_ID: &str = "";
pub mod script_rs {
    #![allow(unused_variables, unused_imports, unused_mut, unused_assignments, clippy::new_without_default)]
    use super::*;
    
    
    pub struct State {
        pub who_value: String,
        pub count_value: String,
    }
    
    impl State {
        pub fn new() -> Self {
            State { who_value: String::new(), count_value: String::new() }
        }
    
        pub fn who(&self) -> String {
            self.who_value.clone()
        }
    
        pub fn how_many(&self) -> String {
            self.count_value.clone()
        }
    }
}
/// This component declares no `Props` struct, so a parent binds nothing to it.
pub struct PropsArg {
    pub values: std::collections::HashMap<String, String>,
}

/// Render this component with callbacks from a parent component.
/// The callbacks map event names to parent handler method names.
pub fn render_with_callbacks(
    props: PropsArg,
    callbacks: &std::collections::HashMap<&'static str, &'static str>,
    _handler_names: &[&'static str],
) -> velox_dom::VNode {
    // Register callbacks in thread-local storage so emit() can find them.
    // set_emit_callbacks lives at the same level as this function (both inside
    // the component module), so no path qualifier is needed.
    set_emit_callbacks(callbacks);
    // Render using the standard props path
    render_with_props(props)
}

/// Render this component with callbacks and slots from a parent component.
/// The callbacks map event names to parent handler method names.
/// The slots map slot names to pre-rendered VNode trees.
pub fn render_with_slots(
    props: PropsArg,
    callbacks: &std::collections::HashMap<&'static str, &'static str>,
    _handler_names: &[&'static str],
    slots: &std::collections::HashMap<&str, velox_dom::VNode>,
) -> velox_dom::VNode {
    set_emit_callbacks(callbacks);
    set_slots(slots);
    render_with_props(props)
}

use super::props_child as PropsChild;


pub fn render() -> velox_dom::VNode {
    render_with(|_| String::new())
}

pub fn render_with<F>(mut resolve: F) -> velox_dom::VNode where F: FnMut(&str) -> String {
    use velox_dom::*;
    h("div", Props::new().set("class", "parent"), { let mut __children: Vec<velox_dom::VNode> = Vec::new();
__children.push(text(" "));
__children.push({ let __props = PropsChild::PropsArg { greeting: resolve("who").clone(), count: (resolve("how_many").clone()).parse().unwrap_or_default() }; PropsChild::render_with_props(__props) });
__children.push(text(" "));
__children
})
}

#[allow(clippy::arc_with_non_send_sync)]
#[allow(unused_variables)]
pub fn render_with_state<F>(state: std::sync::Arc<script_rs::State>, mut resolve: F) -> velox_dom::VNode where F: FnMut(&str) -> String {
    use velox_dom::*;
    h("div", Props::new().set("class", "parent"), { let mut __children: Vec<velox_dom::VNode> = Vec::new();
__children.push(text(" "));
__children.push({ let __props = PropsChild::PropsArg { greeting: resolve("who").clone(), count: (resolve("how_many").clone()).parse().unwrap_or_default() }; PropsChild::render_with_props(__props) });
__children.push(text(" "));
__children
})
}

#[allow(clippy::arc_with_non_send_sync)]
pub fn make_resolve(state: std::sync::Arc<script_rs::State>) -> impl FnMut(&str) -> String {
    move |name: &str| match name {
        "who" => state.who().to_string(),
        "how_many" => state.how_many().to_string(),
        _ => String::new(),
    }
}

#[allow(clippy::arc_with_non_send_sync, clippy::single_match)]
pub fn make_on_event(state: std::sync::Arc<script_rs::State>) -> impl FnMut(&str, Option<&str>) + 'static {
    move |name: &str, payload: Option<&str>| {
        match name {
            _ => {}
        }
    }
}

pub fn render_with_props(props: PropsArg) -> velox_dom::VNode {
    let resolve_props = |key: &str| -> String {
        props.values.get(key).cloned().unwrap_or_default()
    };
    render_with(resolve_props)
}