use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    // veloxc is at <workspace>/veloxc
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn read_template_main(path: &PathBuf) -> String {
    std::fs::read_to_string(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

#[test]
fn template_project_main_rs_uses_w_h() {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("templates/project/src/main.rs");
    let s = read_template_main(&p);
    assert!(
        !s.contains("|_w"),
        "template main.rs must not discard viewport width via |_w: found in {}",
        p.display()
    );
    assert!(
        !s.contains("_h: u32"),
        "template main.rs must not discard viewport height via _h"
    );
    // must declare w,h without underscore
    assert!(
        s.contains("w: u32, h: u32") || s.contains("|w, h|") || s.contains("|w:"),
        "template main.rs must declare w,h viewport params"
    );
}

/// Every shipped example must wire the renderer viewport through `make_view`
/// the same way the `velox init` template does.
const EXAMPLES: [&str; 3] = ["counter", "todo", "showcase"];

#[test]
fn example_main_rs_uses_w_h() {
    for name in EXAMPLES {
        let p = workspace_root().join(format!("examples/{name}/src/main.rs"));
        let s = read_template_main(&p);
        assert!(
            !s.contains("|_w"),
            "{name} main.rs must not contain |_w discard"
        );
        assert!(
            s.contains("w: u32, h: u32"),
            "{name} main.rs must declare w,h viewport params"
        );
    }
}

#[test]
fn cli_init_generate_main_rs_uses_w_h() {
    // The string generated by init.rs is checked by reading the source file
    // to avoid needing to expose a test-only public API.
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("src/commands/init.rs");
    let s = read_template_main(&p);
    // Extract the generate_main_rs raw string region - just assert it does not
    // contain the discarded closure pattern.
    assert!(
        !s.contains("move |_w: u32, _h: u32|"),
        "commands/init.rs generate_main_rs must not contain move |_w, _h| discard"
    );
}

#[test]
fn app_vx_roots_are_viewport_filling() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let ws = workspace_root();
    let paths = [
        manifest.join("templates/project/src/App.vx"),
        ws.join("examples/counter/src/App.vx"),
        ws.join("examples/todo/src/App.vx"),
        ws.join("examples/showcase/src/App.vx"),
    ];
    for p in &paths {
        let s = std::fs::read_to_string(p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
        assert!(
            s.contains("width: 100%"),
            "{} must contain width: 100% for viewport fill",
            p.display()
        );
        // Task 1A requires min-height: 100vh on the root (spec: width:100% / min-height:100vh)
        assert!(
            s.contains("min-height: 100vh") || s.contains("min-height:100vh"),
            "{} must contain min-height: 100vh (Flutter viewport fill contract)",
            p.display()
        );
    }
}

/// Velox-renderer contract is documented in lib.rs doc comment for make_view.
#[test]
fn renderer_make_view_contract_documented() {
    let ws = workspace_root();
    let p = ws.join("velox-renderer/src/lib.rs");
    let s = std::fs::read_to_string(&p).expect("read lib.rs");
    // The doc must mention viewport and w/h dimensions
    assert!(
        s.contains("make_view") && s.contains("viewport"),
        "velox-renderer/src/lib.rs must document make_view viewport contract"
    );
    // Must mention both width/height semantics (vw/vh or w/h)
    assert!(
        s.to_ascii_lowercase().contains("logical")
            || s.contains("w, h")
            || s.contains("vw")
            || s.contains("viewport"),
        "renderer docs must explain logical viewport dimensions"
    );
}
