
[package]
name = "velox-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tools for building Velox applications"
authors = ["fahimaloy"]
license = "MIT"
repository = "https://github.com/fahimaloy/velox"
homepage = "https://velox.dev"

[[bin]]
name = "velox"
path = "src/bin/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
velox-sfc = { path = "../velox-sfc" }
velox-style = { path = "../velox-style" }

[lib]
name = "velox_cli"
path = "src/lib.rs"
