
[package]
name = "velox-cli"
version = "0.1.1"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
# path dep to your parser crate (hyphenated name maps to `velox_sfc` in code)
velox-sfc = { path = "../velox-sfc" }
