use std::path::Path;

use crate::sfc::Sfc;

/// Extremely simple stub codegen that emits a Rust module with raw blocks.
/// Later, you'll compile `<template>` into VNodes and `<style>` into native styles.
pub fn to_stub_rs(sfc: &Sfc, component_name: &str) -> String {
    to_stub_rs_inner(sfc, component_name, None, true)
}

/// Same as `to_stub_rs` but accepts an optional base path for import resolution.
/// When provided, relative imports are resolved from this path instead of CWD.
///
/// The output is wrapped in `pub mod {name} { ... }`, suitable for `include!()`
/// in a standalone build script context.
pub fn to_stub_rs_with_base(sfc: &Sfc, component_name: &str, base_path: Option<&Path>) -> String {
    to_stub_rs_inner(sfc, component_name, base_path, true)
}

/// Same as `to_stub_rs_with_base` but emits the module body *without* the
/// `pub mod {name} { ... }` wrapper. Use this when the caller already manages
/// module declarations (e.g., via `#[path]` attributes in a component tree).
pub fn to_stub_rs_unwrapped(sfc: &Sfc, component_name: &str, base_path: Option<&Path>) -> String {
    to_stub_rs_inner(sfc, component_name, base_path, false)
}

fn to_stub_rs_inner(
    sfc: &Sfc,
    component_name: &str,
    base_path: Option<&Path>,
    wrap_module: bool,
) -> String {
    let t = sfc
        .template
        .as_ref()
        .map(|b| b.content.as_str())
        .unwrap_or("");
    let ss = sfc
        .script_setup
        .as_ref()
        .map(|b| b.content.as_str())
        .unwrap_or("");
    let s = sfc
        .script
        .as_ref()
        .map(|b| b.content.as_str())
        .unwrap_or("");
    let st = sfc.style.as_ref().map(|b| b.content.as_str()).unwrap_or("");

    let name = sanitize_ident(component_name);
    let open = "{";
    let close = "}";

    // Create resolver for component imports using the provided base path.
    // If no base path is given, fall back to the current working directory.
    let resolver_base = base_path
        .map(|p| p.to_path_buf())
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_default());
    let mut resolver = crate::component_resolver::ComponentResolver::new(resolver_base);
    if let Some(script_setup) = &sfc.script_setup {
        resolver.parse_imports(&script_setup.content);
    }

    // NOTE: We intentionally do NOT generate `pub mod {name};` declarations here.
    // The caller (e.g., compile_component_tree in velox-cli) is responsible for
    // generating `#[path = "..."] pub mod ...;` declarations with correct file paths.
    // Generating bare `pub mod` here would conflict with the caller's declarations
    // and cause "file not found for module" errors.

    // A parent component may call `{child}::render_with_callbacks(...)` whenever
    // it attaches an `@event` to a component tag, so every component must expose
    // the emit infrastructure (thread-local callback registry) unconditionally.
    let needs_emit_infra = true;

    // Scoped CSS: when the `<style>` block is declared `scoped`, this component
    // gets a unique `data-v-<hash>` scope id and every CSS selector is prefixed
    // with the matching attribute selector (e.g. `.header` becomes
    // `.header[data-v-abc1ef23]`), confining the rule to this component's
    // elements. The scope id is also exposed as `SCOPE_ID` so the caller can tag
    // rendered VNodes with the same attribute. Unscoped styles pass through
    // unchanged and apply globally.
    let (processed_style, scope_id) = match sfc.style.as_ref() {
        Some(style) if is_scoped(style) => {
            let scope_id = generate_scope_id(component_name);
            (scope_css(st, &scope_id), Some(scope_id))
        }
        _ => (st.to_string(), None),
    };
    let processed_template = t.to_string();

    // Indent level: 4 spaces when wrapped in a module, 0 when unwrapped.
    let indent = if wrap_module { "    " } else { "" };
    let inner_indent = if wrap_module { "        " } else { "    " };

    // Build output manually to allow embedding script_setup as raw Rust.
    let mut out = String::new();
    out.push_str("// @generated by velox-sfc (stub)\n");
    // Always emit inner #![allow] — works both at file-level and inside pub mod {} blocks.
    // When the CLI wraps this in pub mod {name} { ... }, the #![allow] applies to the module body.
    // `unused_variables` covers generated functions whose `state` param is unused
    // in presentational components and v-for index variables in Resolve mode. The
    // clippy allows cover common patterns in generated render code (object-class
    // ternaries, stringified value props, duplicated descendant #[path] modules).
    out.push_str(
        "#![allow(clippy::vec_init_then_push, clippy::arc_with_non_send_sync, \
         clippy::blocks_in_conditions, clippy::duplicate_mod, \
         clippy::match_single_binding, clippy::needless_borrows_for_generic_args, \
         clippy::useless_format, unused_variables)]\n",
    );

    // If any component in the template uses @event, we need the emit module
    if needs_emit_infra {
        out.push_str(&format!("{indent}use std::cell::RefCell;\n"));
        out.push_str(&format!("{indent}use std::collections::HashMap;\n\n"));
        // Emit infrastructure is already indented for module-level (4 spaces).
        // When unwrapped, strip that indentation.
        let emit_code = generate_emit_infrastructure();
        if wrap_module {
            out.push_str(&emit_code);
        } else {
            for line in emit_code.lines() {
                let stripped = line.strip_prefix("    ").unwrap_or(line);
                out.push_str(stripped);
                out.push('\n');
            }
        }
        out.push('\n');
    }

    if wrap_module {
        out.push_str(&format!("pub mod {} {}\n", name, open));
    }
    out.push_str(&format!(
        "{indent}pub const TEMPLATE: &str = r#\"{}\"#;\n",
        escape_raw_string(&processed_template)
    ));
    out.push_str(&format!(
        "{indent}pub const SCRIPT_SETUP: &str = r#\"{}\"#;\n",
        escape_raw_string(ss)
    ));
    out.push_str(&format!(
        "{indent}pub const SCRIPT: &str = r#\"{}\"#;\n",
        escape_raw_string(s)
    ));
    out.push_str(&format!(
        "{indent}pub const STYLE: &str = r#\"{}\"#;\n",
        escape_raw_string(&processed_style)
    ));
    // Emit the component's scope id (empty for unscoped components) so callers
    // can tag rendered VNodes with the same `data-v-*` attribute the scoped
    // selectors rely on.
    out.push_str(&format!(
        "{indent}pub const SCOPE_ID: &str = \"{}\";\n",
        scope_id.unwrap_or_default()
    ));
    if !ss.is_empty() {
        out.push_str(&format!("{indent}pub mod script_rs {{\n{inner_indent}#![allow(unused_variables, unused_imports, unused_mut, unused_assignments, clippy::new_without_default)]\n"));
        out.push_str(&format!("{inner_indent}use super::*;\n"));

        // If this component itself needs emit infrastructure (parent uses @event on it),
        // add the callback type and emit helper
        if ss.contains("define_emits") || ss.contains("emit(") {
            let helpers = generate_component_emit_helpers();
            // helpers are indented for module-level; adjust for inner_indent
            for line in helpers.lines() {
                // Strip the 8-space prefix that was designed for the wrapped format
                let stripped = line
                    .strip_prefix("        ")
                    .unwrap_or(line.strip_prefix("    ").unwrap_or(line));
                out.push_str(&format!("{inner_indent}{stripped}\n"));
            }
        }

        // Insert user code as-is, BUT skip import lines (e.g., `import X from 'Y.vx'`).
        // Import lines are a Velox DSL, not valid Rust. They are already stored
        // in the SCRIPT_SETUP constant above. The caller handles module declarations
        // for imported components via #[path] attributes.
        for line in ss.lines() {
            if is_import_line(line) {
                continue;
            }
            out.push_str(&format!("{inner_indent}{line}\n"));
        }

        // Generate v-model setter methods on the State struct.
        // Parse the template to find v-model directives, then emit setter methods
        // that the event dispatch system can call (e.g., __vmodel_set_counter).
        if let Some(template_block) = &sfc.template
            && let Ok(template_nodes) =
                crate::template_parse::parse_template_to_ast(&template_block.content)
        {
            let vmodels = crate::template_codegen::collect_vmodel_expressions(&template_nodes);
            if !vmodels.is_empty() {
                let setters = crate::template_codegen::generate_vmodel_setters(&vmodels);
                for line in setters.lines() {
                    out.push_str(&format!("{inner_indent}{line}\n"));
                }
            }
        }

        out.push_str(&format!("{indent}}}\n"));
    }

    // Always generate render_with_callbacks so a parent can pass event callbacks
    // regardless of whether this component declares emits.
    let render_cb = generate_render_with_callbacks_inside_module();
    // The template has 4-space indentation; adjust to indent level
    for line in render_cb.lines() {
        let stripped = line.strip_prefix("    ").unwrap_or(line);
        out.push_str(&format!("{indent}{stripped}\n"));
    }

    // If the template has <slot> elements, also generate render_with_slots
    // (slots-only variant) so parents can pass slot content without callbacks.
    let has_slots = t.contains("<slot");
    if has_slots {
        let render_slots = generate_render_with_slots_only_inside_module();
        for line in render_slots.lines() {
            let stripped = line.strip_prefix("    ").unwrap_or(line);
            out.push_str(&format!("{indent}{stripped}\n"));
        }
    }

    if wrap_module {
        out.push_str(close);
        out.push('\n');
    }
    out
}

/// Check if a line is a Velox component import statement.
/// Matches patterns like:
///   import MyButton from './components/Button.vx'
///   import { Button, Card } from './components.vx'
fn is_import_line(line: &str) -> bool {
    let trimmed = line.trim();
    trimmed.starts_with("import ") && trimmed.contains(" from ")
}

/// True when the `<style>` block is declared `scoped`, which requires
/// attribute-scoped selectors and a per-component scope id.
pub fn is_scoped(style: &crate::sfc::StyleBlock) -> bool {
    style.attrs.iter().any(|a| a.name == "scoped")
}

/// Generate a unique, stable scope id for a component (Vue-style
/// `data-v-<hash>`). The 32-bit FNV-1a hash of the component name yields a
/// distinct id per component and is deterministic, so generated code is
/// reproducible and golden-file stable.
pub fn generate_scope_id(component_name: &str) -> String {
    let mut hash: u32 = 0x811c9dc5;
    for b in component_name.bytes() {
        hash ^= u32::from(b);
        hash = hash.wrapping_mul(0x01000193);
    }
    format!("data-v-{:08x}", hash)
}

/// Rewrite a CSS stylesheet so every top-level selector carries the scope
/// attribute appended to its descendant-most (rightmost) part:
///
/// ```css
/// .header h1 { ... }  ->  .header h1[data-v-abc123] { ... }
/// h1, .a { ... }      ->  h1[data-v-abc123], .a[data-v-abc123] { ... }
/// ```
///
/// Declaration blocks are copied verbatim. Appending the attribute to the last
/// selector part matches how the velox-style parser matches rules (it checks
/// the rightmost part against the target element), so a rule applies only to
/// VNodes tagged with the matching `data-v-*` attribute.
fn scope_css(css: &str, scope_id: &str) -> String {
    let attr = format!("[{scope_id}]");
    let mut out = String::with_capacity(css.len());
    let mut depth: usize = 0;
    let mut prelude = String::new();
    for c in css.chars() {
        match c {
            '{' => {
                if depth == 0 {
                    out.push_str(&scope_selector_list(&prelude, &attr));
                } else {
                    out.push_str(&prelude);
                }
                prelude.clear();
                depth += 1;
                out.push(c);
            }
            '}' => {
                out.push(c);
                depth = depth.saturating_sub(1);
            }
            _ => {
                if depth == 0 {
                    prelude.push(c);
                } else {
                    out.push(c);
                }
            }
        }
    }
    out.push_str(&prelude);
    out
}

/// Append the scope attribute to each selector in a comma-separated selector
/// list. Non-selector text between rules is carried through unchanged.
fn scope_selector_list(prelude: &str, attr: &str) -> String {
    let mut out = String::with_capacity(prelude.len() + 32);
    for (i, sel) in prelude.split(',').enumerate() {
        if i > 0 {
            out.push(',');
        }
        out.push_str(&scope_single_selector(sel, attr));
    }
    out
}

/// Append `[data-v-<scope>]` to the descendant-most (rightmost) part of a single
/// selector. Child combinators (`>`) are dropped, matching how the velox-style
/// parser lowers selectors to descendant chains.
fn scope_single_selector(sel: &str, attr: &str) -> String {
    let mut parts: Vec<&str> = Vec::new();
    for tok in sel.split_whitespace() {
        if tok == ">" {
            continue;
        }
        parts.push(tok);
    }
    if parts.is_empty() {
        return sel.to_string();
    }
    let last = parts.len() - 1;
    let mut out = String::with_capacity(sel.len() + attr.len());
    for (i, p) in parts.iter().enumerate() {
        if i > 0 {
            out.push(' ');
        }
        out.push_str(p);
        if i == last {
            out.push_str(attr);
        }
    }
    out
}

/// Generate the global emit infrastructure: Callbacks type, emit function,
/// set_callback function, and slots thread-local using thread-local storage.
fn generate_emit_infrastructure() -> String {
    r#"    /// Type alias for callback maps passed to child components.
    pub type Callbacks = std::collections::HashMap<&'static str, &'static str>;

    // Thread-local callback registry for emit system.
    // Stores event name -> handler function name mappings.
    thread_local! {
        static EMIT_CALLBACKS: RefCell<HashMap<String, String>> = RefCell::new(HashMap::new());
        static SLOTS: RefCell<HashMap<String, velox_dom::VNode>> = RefCell::new(HashMap::new());
    }

    /// Register callbacks for the current render scope.
    /// Called by `render_with_callbacks` before rendering a child component.
    pub fn set_emit_callbacks(callbacks: &Callbacks) {
        EMIT_CALLBACKS.with(|cell| {
            let mut map = cell.borrow_mut();
            map.clear();
            for (k, v) in callbacks {
                map.insert(k.to_string(), v.to_string());
            }
        });
    }

    /// Store slots for the current render scope so `<slot>` elements can find them.
    pub fn set_slots(slots: &std::collections::HashMap<&str, velox_dom::VNode>) {
        SLOTS.with(|cell| {
            let mut map = cell.borrow_mut();
            map.clear();
            for (k, v) in slots {
                map.insert(k.to_string(), v.clone());
            }
        });
    }

    /// Emit an event from a child component to its parent.
    /// Looks up the registered callback and returns the handler name.
    /// The caller is responsible for invoking the handler on their State.
    pub fn emit(event: &str, _payload: &str) -> Option<String> {
        EMIT_CALLBACKS.with(|cell| {
            let map = cell.borrow();
            map.get(event).cloned()
        })
    }

    /// Look up slot content by name. Returns the slot VNode if found,
    /// otherwise calls the fallback closure.
    pub fn render_slot(
        name: &str,
        fallback: impl FnOnce() -> velox_dom::VNode,
    ) -> velox_dom::VNode {
        SLOTS.with(|cell| {
            let map = cell.borrow();
            if let Some(v) = map.get(name) {
                return v.clone();
            }
            drop(map);
            fallback()
        })
    }"#
    .to_string()
}

/// Generate emit helpers that go inside the component's script_rs module.
fn generate_component_emit_helpers() -> String {
    r#"
        /// Emit an event to the parent component's handler.
        /// Looks up the callback name from the thread-local registry.
        pub fn emit(event: &str, payload: &str) {
            if let Some(_handler_name) = super::emit(event, payload) {
                // The handler will be invoked via the parent's on_event dispatcher.
                // The handler_name corresponds to a method on the parent's State.
            }
        }
"#
    .to_string()
}

/// Generate `render_with_callbacks` function that accepts callbacks from a parent.
/// Also generates `render_with_slots` overloads for components that accept slots.
/// This goes INSIDE the module (before the closing brace).
fn generate_render_with_callbacks_inside_module() -> String {
    r#"
    /// Render this component with callbacks from a parent component.
    /// The callbacks map event names to parent handler method names.
    pub fn render_with_callbacks(
        props: std::collections::HashMap<&str, String>,
        callbacks: &std::collections::HashMap<&'static str, &'static str>,
        _handler_names: &[&'static str],
    ) -> velox_dom::VNode {
        // Register callbacks in thread-local storage so emit() can find them.
        // set_emit_callbacks lives at the same level as this function (both inside
        // the component module), so no path qualifier is needed.
        set_emit_callbacks(callbacks);
        // Render using the standard props path
        render_with_props(props)
    }

    /// Render this component with callbacks and slots from a parent component.
    /// The callbacks map event names to parent handler method names.
    /// The slots map slot names to pre-rendered VNode trees.
    pub fn render_with_slots(
        props: std::collections::HashMap<&str, String>,
        callbacks: &std::collections::HashMap<&'static str, &'static str>,
        _handler_names: &[&'static str],
        slots: &std::collections::HashMap<&str, velox_dom::VNode>,
    ) -> velox_dom::VNode {
        set_emit_callbacks(callbacks);
        set_slots(slots);
        render_with_props(props)
    }
"#
    .to_string()
}

/// Generate `render_with_slots` function that accepts props and slots from a parent.
/// This is called when a parent passes slot content to a child component
/// (without callbacks). Goes INSIDE the module (before the closing brace).
fn generate_render_with_slots_only_inside_module() -> String {
    r#"
    /// Render this component with slot content from a parent component.
    /// The slots map maps slot names to pre-rendered VNode trees.
    pub fn render_with_slots(
        props: std::collections::HashMap<&str, String>,
        slots: &std::collections::HashMap<&str, velox_dom::VNode>,
    ) -> velox_dom::VNode {
        set_slots(slots);
        render_with_props(props)
    }
"#
    .to_string()
}

fn sanitize_ident(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    for (i, ch) in raw.chars().enumerate() {
        if (i == 0 && ch.is_ascii_digit()) || !is_ident_char(ch) {
            out.push('_');
        } else {
            out.push(ch.to_ascii_lowercase());
        }
    }
    if out.is_empty() { "_comp".into() } else { out }
}

fn is_ident_char(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_'
}

/// Escape content for use in r#"..."# raw string literals.
/// The sequence "# would terminate the raw string early, so we escape it.
fn escape_raw_string(s: &str) -> String {
    s.replace("\"#", "\"\\#")
}
